# Murano Product Spec File - Smart Lighbulb Example Application


resources:
-   alias: temperature
    format: float
-   alias: humidity
    format: float
-   alias: state
    format: integer
    initial: 0
-   alias: uptime
    format: integer
-   alias: leds
    format: integer
-   alias: party_led
    format: integer
-   alias: count
    format: integer